from mongoengine import *
from datetime import datetime

class CircleFace(Document):
	pebble_id = StringField(max_length=256, required=True, unique=True)
	sn = StringField(max_length=18, required=True, unique=True)
	created_time = DateTimeField(default=datetime.now, required=True)
	valid = BooleanField(default=True, required=True)
	pay_time = DateTimeField()
	use_time = IntField(default=0)
	city_name = StringField(max_length=512, required=False)
	watch_style = StringField(max_length=32, required=False)
	vibration_period = IntField(default=0, required=True)
	not_alert = BooleanField(default=True, required=True)
	not_alert_start = IntField(default=19, required=True)
	not_alert_end = IntField(default=8, required=True)
	invert_color = StringField(max_length=4, required=False)
	watch_color = StringField(max_length=8, required=False)
	bluetooth_alert = BooleanField(default=True, required=True)

	countday_check = BooleanField(default=False, required=False)
	mydate_name = StringField(max_length=512, required=False)
	mydate = StringField(max_length=16, required=False)
	mytime = StringField(max_length=16, required=False)
	countday_type = StringField(max_length=4, required=False)

	note_check = BooleanField(default=False, required=False)
	mytxt1 = StringField(max_length=512, required=False)
	mytxt2 = StringField(max_length=512, required=False)

	weather_station = StringField(max_length=4, required=False)

	today_weather_check = BooleanField(default=True, required=False)
	health_check = BooleanField(default=True, required=False)
	health_value = StringField(max_length=128, required=False)
	tap_check = BooleanField(default=True, required=False)
	hour24_check = BooleanField(default=True, required=False)
	timeline_news_check = BooleanField(default=False, required=False)
	timeline_english_check = BooleanField(default=True, required=False)
	timeline_zhongchao_check = BooleanField(default=False, required=False)
	timeline_huangli_check = BooleanField(default=False, required=False)
	switch_bw_check = BooleanField(default=False, required=False)
	language = StringField(max_length=128, required=False)
	t_unit = StringField(max_length=16, required=False)

	show_temperature_check = BooleanField(default=True, required=False)
	show_day_check = BooleanField(default=True, required=False)
	show_bluetooth_check = BooleanField(default=True, required=False)
	show_battery_check = BooleanField(default=True, required=False)
	show_second_check = BooleanField(default=True, required=False)
	show_aqi_check = BooleanField(default=True, required=False)
	display_value = StringField(max_length=128, required=False)
	show_nongli_check = BooleanField(default=False, required=False)
	
	bg_color = StringField(max_length=16, required=False)
	hour_bg_color = StringField(max_length=16, required=False)
	hour_text_color = StringField(max_length=16, required=False)
	minute_bg_color = StringField(max_length=16, required=False)
	second_bg_color = StringField(max_length=16, required=False)
	minute_text_color = StringField(max_length=16, required=False)
	circle_color = StringField(max_length=16, required=False)
	other_text_color = StringField(max_length=16, required=False)
	battery_color = StringField(max_length=16, required=False)
	shake_sens = StringField(default='1', required=False)
	bluetooth_icon = StringField(max_length=16, required=False)

class CircleAccount(Document):
	account_id = StringField(max_length=256, required=True, unique=True)
	sn = StringField(max_length=18, required=True, unique=True)
	created_time = DateTimeField(default=datetime.now, required=True)
	expired_time = DateTimeField(required=False)
	valid = BooleanField(default=True, required=True)
	pay_time = DateTimeField()
	timeline_token = StringField(max_length=256, required=False)
	version_number = StringField(max_length=32, required=False)
	qrcode_image_path = StringField(max_length=256, required=False)